name: serverpod_admin_app
description: Prebuilt Flutter web app for serving Serverpod Admin from a Serverpod backend.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.10.3 <4.0.0'
  flutter: '>=3.38.4'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  serverpod_admin_client: ^1.0.14
  serverpod_admin_dashboard:
    path: ../serverpod_admin_dashboard
  serverpod_auth_core_client: ^4.0.0-beta.1
  serverpod_auth_idp_client: ^4.0.0-beta.1
  serverpod_auth_idp_flutter: ^4.0.0-beta.1
  serverpod_client: ^4.0.0-beta.1
  serverpod_flutter: ^4.0.0-beta.1
  web: ^1.1.1

dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter

dependency_overrides:
  serverpod_admin_client:
    path: ../serverpod_admin_client

flutter:
  uses-material-design: true
